struct Cell
{
    uint type;
    uint data1;
    uint data2;
    uint clock;
};

int chunk_size;
RWTexture2D<float4> texture_out;
StructuredBuffer<Cell> cells;
StructuredBuffer<float4> cell_type_colors;

#pragma kernel render_chunk

[numthreads(8, 8, 1)]
void render_chunk(uint2 id : SV_DispatchThreadID)
{
    Cell cell = cells[id.x + (id.y * chunk_size)];
    
    float4 resultColor = cell_type_colors[cell.type];

    texture_out[id.xy] = resultColor;
}